### ISSUE TITLE
Highlight a piece of text

### ISSUE THREAD

**Issue by AjaxZhan** [TaTo30/vue-pdf#90] opened 2024-01-25 09:16 UTC
This js library is very useful for me.However, how can I highlight a piece of text instead of certain words, in other words, can I use this library to highlight an area?

**Comment by TaTo30** [comment] 2024-02-16 21:03
There aren't a way to highlight an area using the library so far, but if you can get the divs you need to highlight you can append the highlight class:
```js
span.className = 'highlight appended'
```
[highlight.ts](https://github.com/TaTo30/vue-pdf/blob/master/src/components/utils/highlight.ts)

**Comment by TaTo30** [comment] 2024-05-05 23:47
I will close this Issue since is a duplicate of #98

**Closed by TaTo30** 2024-05-05 23:47 UTC
