### ISSUE TITLE
Annotation Events 

### ISSUE THREAD

**Issue by irelib** [TaTo30/vue-pdf#133] opened 2024-08-14 08:45 UTC
Why am I using the Annotation Events, when clicking on the directory (type is internal-link), the referencedPage obtained is incorrect. No matter which directory you click, you will get the referencedPage of the first directory. I wrote it exactly according to the official document, and the results achieved were different. I don't know if this is a bug.

I have attached my code file and pdf file
[index.zip](https://github.com/user-attachments/files/16610200/index.zip)

**Comment by TaTo30** [comment] 2024-08-17 21:29
Duplicate of #126 and #129

**Closed by TaTo30** 2024-08-17 21:29 UTC
